### ISSUE TITLE
TypeError: strToSplit.split is not a function

### ISSUE THREAD

**Issue by tux86** [robessog/cfn-resolver-lib#117]
**Bug Intro**

To  reproduce this a error you should have  **serverless-appsync-simulator** (includes **cfn-resolver-lib**)  and **serverless-offline** plugins and   cloudfront resource configuration for  appsync.

When starting offline mode with **serveress offline start** I got this error: 

```
AppSync Simulator: TypeError: strToSplit.split is not a function
```

**Bug description**

The bug is caused by appsync-simulator if you have  **Fn::Split** CF function in  **DomainName** of **Origin** section. See example below.

```
Resources:
  PublicApiDistribution:
        ......
        Origins:
          - Id: PublicApiOrigin
            DomainName:
              Fn::Select:
                - '2'
                - Fn::Split:
                    - /
                    - Fn::GetAtt:
                        - "Eventapipub${sls:stage}GraphQlApi"
                        - GraphQLUrl
```

**Temporary workaround**

Currently the only solution do disable this error in offline mode is to comment cf code for distribution.
