### ISSUE TITLE
TypeError: FnSplit is not a constructor

### ISSUE THREAD

**Issue by kevinsperrine** [robessog/cfn-resolver-lib#24]
My YAML file contains a split inside of a join to rename a cognito identity pool (since `-` isn't a valid name character), but I get an error that FnSplit is not a constructor.

```
IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName:
          Fn::Join: [' ', Fn::Split: ['-', '${self:service}-${self:provider.stage}-identity-pool']]
```
