### ISSUE TITLE
TypeError: strToSplit.split is not a function

### ISSUE THREAD

**Issue by sasuke0209** [robessog/cfn-resolver-lib#98]
Hi, I found a bug.
In my YML file, I have defined the Cfn `Fn::GetAtt` function in the source string of Cfn `Fn::Split` function, but
I get an error saying that strToSplit.split is not a function.

```
ApiGatewayMethod:
      Type: AWS::ApiGateway::Method
      Integration: 
             ⋮
          Uri: !Sub
            - arn:aws:apigateway:${AWS::Region}:${GraphQLApiSubDomain}.appsync-api:path/graphql
              GraphQLApiSubDomain: !Select [0, !Split [".", !Select [1, !Split ["https://", !GetAtt GraphQlApi.GraphQLUrl]]]]
```

If you comment out the line, the error will no longer be displayed.
